### ISSUE TITLE
🐛 a promise was created in a handler at src/ChannelWrapper.js:236:18 but was not returned from it

### ISSUE THREAD

**Issue by A-Tokyo** [benbria/node-amqp-connection-manager#54]
## Description:

After creating a channel using connection.createChannel and then using channelWrapper.sendToQueue, This error is printed.
```
(node:42976) Warning: a promise was created in a handler at /Users/User/.../ProjectName/node_modules/amqp-connection-manager/src/ChannelWrapper.js:236:18 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/Users/User/.../ProjectName/node_modules/bluebird/js/release/promise.js:196:13)
```

### Environment:
- Node.js: v10.10.0

### Note:
Using Bluebird

**Comment by A-Tokyo** [comment]
Upgrading BlueBird from 3.4.7 to 3.5 solved the issue 👍

**Comment by moltar** [comment]
Getting a load of these too:

```
(node:30771) Warning: a promise was created in a handler at .../node_modules/amqp-connection-manager/lib/ChannelWrapper.js:344:18 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (.../node_modules/bluebird/js/release/promise.js:196:13)

```

It's here:

```js
        }).then(result => {
            this._messages.shift();
            message.resolve(result);

            // Send some more!
            this._publishQueuedMessages(workerNumber);       // <-- THIS LINE
        }, err => {
```

Is there a reason why it's not returning?

Thanks.
